#### 镜像上传
# 仓库私服： 示例jontymax (替换成你自己的仓库地址)
# 第一步：上传镜像到docker仓库
#docker tag jeecg-boot-mysql:latest jontymax/jeecg-boot-mysql:latest
#docker tag jeecg-boot-system:latest jontymax/jeecg-boot-system:latest
#docker tag jeecg-boot-vue:latest jontymax/jeecg-boot-vue:latest

#docker push jontymax/jeecg-boot-mysql:latest
#docker push jontymax/jeecg-boot-system:latest
#docker push jontymax/jeecg-boot-vue:latest

# 第二步：将此yml文件上传服务器，执行启动命令 docker-compose -f ./docker-compose-server.yml up
version: '3'

networks:
  net:
  internal-network:
    external: true

services:
  jeecg-boot-mysql:
    image: jontymax/jeecg-boot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - net
      - internal-network
    container_name: jeecg-boot-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    ports:
      - 3306:3306

  jeecg-boot-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    networks:
      - net
      - internal-network
    container_name: jeecg-boot-redis

  jeecg-boot-system:
    image: jontymax/jeecg-boot-system
    restart: always
    networks:
      - net
      - internal-network
    container_name: jeecg-boot-system
    depends_on:
      - jeecg-boot-mysql
      - jeecg-boot-redis
    volumes:
      - /data/config:/jeecg-boot/config
    ports:
      - 8080:8080

  jeecg-boot-vue:
    image: jontymax/jeecg-boot-vue
    restart: always
    networks:
      - net
      - internal-network
    container_name: jeecg-boot-vue
    depends_on:
      -  jeecg-boot-system
    ports:
      - 80:80
